### ISSUE TITLE
Hi Daniel

### ISSUE THREAD

**Issue by arxdsilva** [drgomesp/happendb#1]
This is entire part of the interview process, there are no time constraints from my side, so you can provide fixes and/or discussion on your own time, at your own pace. i'll be opening issues according to changes that we'd like for you to implement.

**Comment by drgomesp** [comment]
- [x] Docker support (#7)
- [x] ~Makefile~ Taskfile (#8) 
- [x] Graceful shutdown (#9) 
- [x] Hexagonal arch (#10)
- [x] Tests (#8)

**Comment by drgomesp** [comment]
@arxdsilva I have made some comments on a couple of individual PRs and also I'd be totally willing to have a chat about all of the topics and changes, especially the hexagonal/DDD one, if you wish. However I do believe that the changes and the commits and descriptions should be enough to cover everything you mentioned. 

Please do let me know if there's anything I forgot :)

**Comment by arxdsilva** [comment]
Thank you @drgomesp for the fast response and the updated code.

**Comment by drgomesp** [comment]
Thank you @arxdsilva for the very nice approach and for helping me improve my own code.
Hopefully you liked the changes so that we can colaborate more in then future :D
