### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by arxdsilva** [drgomesp/happendb#3]
Please create a Makefile which purpose is to help colleagues (without talking to you) to run all steps of the project and work independently:

build
unit_test
run
docker?
lint?
etc

**Comment by drgomesp** [comment]
I have indeed created a [Taskfile](https://taskfile.dev/) instead, which from a Go's perspective, is just easier and more cross-platform. 

I will be updating it with the commented tasks.

**Comment by drgomesp** [comment]
Readme now has instructions and more info @arxdsilva .
